Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Create a forwarded port mapping.
  config.vm.network "forwarded_port", guest: 80, host: 420

  # Create a private network
  config.vm.network "private_network", ip: "192.168.33.10"

  # Share an additional folder to the guest VM.
  config.vm.synced_folder "./html", "/var/www/html" 

  config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", path: "./script/script.sh"

end
